export { env } from '@/lib/config/env'

export { ApiError, api, serverApi, BFF_BASE } from './client'

export { authApi } from './auth'
export { studentsApi } from './students'
export { teachersApi } from './teachers'
export { parentsApi } from './parents'
export { feesApi, paymentsApi } from './fees'
export { attendanceApi } from './attendance'
export { leaveApi } from './leave'
export { admissionsApi } from './admissions'
export { libraryApi } from './library'
export { transportApi } from './transport'
export { payrollApi } from './payroll'
export { examsApi } from './exams'
export { notificationsApi } from './notifications'
export { dashboardApi } from './dashboard'
export { academicsApi } from './academics'
export { timetableApi } from './timetable'
export { hostelApi } from './hostel'
export { inventoryApi } from './inventory'
export { parentPortalApi } from './parent-portal'
export { teacherPortalApi } from './teacher-portal'
export { studentPortalApi } from './student-portal'
export { uploadFile } from './uploads'

export type * from './types'
